-- ============================================
-- PART 1: ADD NEW MOVEMENT TYPES TO ENUM
-- ============================================
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'ORDER_RESERVE';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'ORDER_UNRESERVE';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'DRIVER_PICKUP';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'DELIVERY_ACCEPTED';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'DRIVER_RETURN_SUBMIT';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'RUNNER_RETURN_ACK';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'INBOUND_RECEIVE';
ALTER TYPE movement_type ADD VALUE IF NOT EXISTS 'STOCK_CORRECTION';